# Generated by Django 4.1 on 2023-08-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lecoq2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ItemIngrediente",
            fields=[
                ("codigo", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ItemTabelaNutricional",
            fields=[
                ("cod", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TabelaNutricionalProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peso", models.DecimalField(decimal_places=2, max_digits=6)),
                ("porcentagemVD", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "codigo_nutri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lecoq2.itemtabelanutricional",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="produto", name="codigo_tabela_ingredientes",
        ),
        migrations.RemoveField(model_name="produto", name="codigo_tabela_nutricional",),
        migrations.DeleteModel(name="Ingredientes",),
        migrations.DeleteModel(name="TabelaNutricional",),
        migrations.AddField(
            model_name="tabelanutricionalproduto",
            name="codigo_prod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lecoq2.produto"
            ),
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="codigo_ingrediente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lecoq2.itemingrediente"
            ),
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="codigo_prod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lecoq2.produto"
            ),
        ),
    ]
