# Generated by Django 4.1 on 2023-08-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lecoq2", "0002_ingrediente_itemingrediente_itemtabelanutricional_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tabelanutricionalproduto", old_name="peso", new_name="valor",
        ),
    ]
