# Generated by Django 4.1 on 2023-08-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecoq2", "0006_pedido_data_alteracao_pedido_data_criacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="itenspedido",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pedido",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
