# Generated by Django 4.1 on 2023-08-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lecoq2", "0008_itenspedido_total"),
    ]

    operations = [
        migrations.RemoveField(model_name="itenspedido", name="total",),
    ]
