# Generated by Django 4.1 on 2023-08-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecoq2", "0010_cliente_dia_semana_entrega_cliente_hora_intervalo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="observacao",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
