# Generated by Django 4.1 on 2023-08-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecoq2", "0011_alter_pedido_observacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="itenspedido",
            name="quantidade_dev",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
